# usr/bin/env python

# Put a list with the name of the directory
# Right now is [4 Digit Code] [Course complete name]

from homework import Homework

# Comment already done classes
course_names = (
    # 'DTC0 DIBUJO TECNICO',
    # 'LPR0 LOGICA PREPOSICIONAL',
    # 'CGR0 CULTURA GENERAL',
    # 'QTE0 QUIMICA TECNICA',
    # 'TIC1 TECNOLOGIA DE LA INFORMACION Y COMUNICACION 1',
    # 'IAF0 INTRODUCCION A LA FISICA',
    # 'ING1 INGLES 1',
    # 'MAT1 MATEMATICA 1',
    # 'REO0 REDACCION Y ORTOGRAFIA',
    # 'TIC2 TECNOLOGIA DE LA INFORMACION Y COMUNICACION 2',
    # 'FCA0 FILOSOFIA DE LA CALIDAD',
    'FCA1 FISICA 1',
    'ING2 INGLES 2',
    'MAT2 MATEMATICA 2',
    'PRG1 PROGRAMACION 1',
    'ETI0 ETICA',
    'FCA2 FISICA 2',
    'MAT3 MATEMATICA 3',
    'PRG2 PROGRAMACION 2',
    'SON0 SOCIEDAD DE LA INFORMACION',
    'DDB0 DISEÑO DE BASE DE DATOS',
    'FCA3 FISICA 3',
    'HDC0 HARDWARE DE COMPUTADORAS',
    'MAT4 MATEMATICA 4',
    'PRG3 PROGRAMACION 3',
    'ADD0 ADMINISTRACION DE BASE DE DATOS',
    'DIR0 DISPOSITIVOS DE REDES',
    'EST1 ESTADISTICA 1',
    'LDM0 LENGUAJE DE MAQUINAS',
    'PRG4 PROGRAMACION 4',
    'ASI1 ANALISIS DE SISTEMAS 1',
    'FES0 FISICA ESTRUCTURAL',
    'IEC0 INGENIERIA ECONOMICA',
    'PHA0 PROGRAMACION PARA HARDWARE',
    'SIO0 SISTEMAS OPERATIVOS',
    'ASI2 ANALISIS DE SISTEMAS 2',
    'IDS0 INFRAESTRUCTURA DE SERVIDORES',
    'IOP1 INVESTIGACION DE OPERACIONES',
    'REC0 REDES DE COMPUTADORAS',
    'SIF0 SEGURIDAD INFORMATICA',
    'ASE1 ASIGNATURA ELECTIVA 1',
    'ASE2 ASIGNATURA ELECTIVA 2',
    'EMN0 EMPRENDIMIENTO E INNOVACION',
    'FOE0 FORMULACION Y EVALUACION DE PROYECTOS',
    'ISW1 INGENIERIA DE SOFTWARE 1',
    'ASE3 ASIGNATURA ELECTIVA 3',
    'ASE4 ASIGNATURA ELECTIVA 4',
    'GEM0 GESTION EMPRESARIAL',
    'ISW2 INGENIERIA DE SOFTWARE 2',
)


def create_directories():
    for course in course_names:
        homework: Homework = Homework(course)
        homework.create_homework()


if __name__ == '__main__':
    create_directories()
